### ISSUE TITLE
How to run this application?

### ISSUE THREAD

**Issue by AboOod88** [ThomasValerrianPasca/LTE_Energy_Module_NS3#1]
Hi Dear,

Your application is interesting but I would love to provide us steps how to run the application and publish it with your code?

**Comment by ThomasValerrianPasca** [comment]
Hello Friend,
I have enabled monitoring energy for all the UEs which are created using LTE helper. Please check the code "lena-simple-epc-enabled-energy-by-default.cc" in the scratch folder. Run that file and observe the energy stats are printed for fixed time interval.. Hope I answered your question.. For any further queries write to me.. Thank You
